### PR TITLE
Add support to S8000 S8003

### PR DESCRIPTION
**Pull request by f0xforce**
Nice worked

### CODE REVIEW

**Comment by 0x41c** [comment]
Bro why did you close this?

**Comment by Rusty2183** [comment]
??

**Comment by 0x41c** [comment]
why? this is great! adding support for iPhone 6s is awesome but its not committed and closed?

**Comment by 0x41c** [comment]
> Nice worked

Did it actually work?

**Comment by riptl** [comment]
@Regularcheckm8 Looking at the changes, it's just migration to Python 3 and some notes. In any case you can try out to-be-merged branch directly https://github.com/geohot/ipwndfu

**Pull request closed without merging**
